### ISSUE TITLE
Identifiers are parsed as keywords sometimes

### ISSUE THREAD

**Issue by segeljakt** [artagnon/tree-sitter-mlir#1]
Sometimes identifiers are parsed as keywords:

<img width="490" alt="image" src="https://github.com/artagnon/tree-sitter-mlir/assets/15143039/22109d29-88e9-4b8f-ab49-709526a99cb3">

<img width="247" alt="image" src="https://github.com/artagnon/tree-sitter-mlir/assets/15143039/1799d338-0f41-419a-bf07-8a0c0c0eef82">

I think it could be solved with 

```js
grammar({
   word: $ => $.bare_id,
// ...
})
```

Would it be possible to add or does it interfere with other rules?

**Comment by artagnon** [comment]
Thanks for reporting the issue, and sorry about the delayed response. Unfortunately, the solution you suggested breaks all tests, and I'm currently investigating how this could be fixed.

**Comment by artagnon** [comment]
Okay, the issue isn't in the core parser, but rather in highlights.scm. I'll have a look at the features tree-sitter supports in highlights.scm, for a potential fix.

**Comment by artagnon** [comment]
The first issue was a bug that's now been fixed, but the second issue can't be fixed, because the parser fails on a downstream dialect, and tree-sitter's error-recovery isn't good enough. Thanks again for reporting!
